### PR TITLE
Fix s3 endpoint formating

### PR DESCRIPTION
**Pull request by m0ssc0de**
Use `loc.host` as `endpoint`, we will get an error like this.

`Jan 16 23:41:47.400 ERROR cargo_fetcher::mirror: failed to mirror crates: failed to list objects: Error during dispatch: error trying to connect: tls handshake eof: Error during dispatch: error trying to connect: tls handshake eof`

### CODE REVIEW

**Review by Jake-Shadle — CHANGES_REQUESTED** [review]
Can you add a test for what the URL should look like when targetting s3 on localhost?

**Comment by Jake-Shadle** [comment]
It looks like you need to rebase your branch.

**Comment by m0ssc0de** [comment]
It should be fast-forward now.

**Comment by lpil** [comment]
Possibly a silly question but with this change how do we use this with an S3 format API from a vendor other than AWS? i.e. Minio, DigitalOcean, BackBlaze, Wasabi, etc.

**Comment by m0ssc0de** [comment]
Yes. You are right. I though the same question when developing.

At the beginning, I plan to use regex to validate the URL and get s3 parameters(bucket, region...) from the URL.

According https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html, the s3 URL have two styles, path-style and virtual-hosted–style. They looks like these:

- path-style `https://s3.us-west-2.amazonaws.com/mybucket/puppy.jpg`
- virtual-hosted–style `https://my-bucket.s3.us-west-2.amazonaws.com/puppy.png`
    - `s3` + `.` + `{Region}`

We are using a older or undocumented, but published virtual-hosted-style.

- `http(s)?://<bucket>.s3(-<region>).<host>(/<prefix>)?` from [README](https://github.com/EmbarkStudios/cargo-fetcher/tree/da63d3ac1882fe7352b88795d84caaa494e8e7cb#s3)
    - `s3` + `-` + `{Region}`

Because user could get a documented virtual-hosted-style URL from aws console easily. I wanted to support this manner first. But the way we parse the s3 URL is using `.` splite the input URL. In this way, I couldn't determine the word after `s3.` is a region or a part of a domain. So without changing the previous cli interface, I add a regex to support validating two kind of s3 virtual-hosted-style URL firstly.

Yes, the regex contains `amazonaws.com`. This will make the non-aws s3 API invalid. So let us remove the aws domain away or some new solutions? Do you have any suggestions? @lpil

**Comment by lpil** [comment]
Hey @m0ssc0de. Thanks for the extra info there, makes a lot of sense. I personally would lean towards the path style, but I'm not sure what is best for this project as I'm largely unfamiliar with it, I just had that question about other object stores. I'll leave it up to Jake to decide what's best.

Thanks everyone!

**Comment by m0ssc0de** [comment]
Thank @lpil 's great suggestion. I rethink the whole problem in my view.

In the beginning, I found the s3 backend is not working before transfer it into a sans-io pattern. I don't know whether someone is using it. I guess the user mostly uses the GCS backend. So, first of all, make the official s3 backend works. 

`cargo-fetcher` supports 3 kinds of object storage backend—obviously, the more, the better. I agree with @lpil  's suggestion. We should support s3-like backends. Maybe other private object storage API, such as swift, should also be considered.

But time is pressured. If @lpil has an important backend to support, I'm happy to contribute to it first.

**Pull request closed without merging**
